image: debian/stable
packages:
  - emacs
  - elpa-htmlize
  - rsync
  - texinfo
  - texlive
sources:
  - https://git.sr.ht/~bzg/orgweb
  - https://git.savannah.gnu.org/git/emacs/org-mode.git
secrets:
  - 7a38e4c8-2b08-446e-a478-2a114a50db86
tasks:
  - install: |
      cd org-mode
      git checkout bugfix
      cat mk/default.mk > local.mk
      cat mk/server.mk >> local.mk
      mkdir -p upload/guide upload/manual
      make autoloads
      make doc-up
      wget -O orgweb/org-mode.tar.gz https://git.savannah.gnu.org/cgit/emacs/org-mode.git/snapshot/org-mode-$(git describe --abbrev=0).tar.gz
      cd ../orgweb
      ./publish.sh
  - upload: |
      rsync -e "ssh -o StrictHostKeyChecking=no" -av orgweb/* bzg.fr:/home/build/orgmode/
      rsync -e "ssh -o StrictHostKeyChecking=no" -av org-mode/upload/* bzg.fr:/home/build/orgmode/
triggers:
  - action: email
    condition: failure
    to: bzg@gnu.org
