#+TITLE:     Org mode for Emacs -- Release notes
#+AUTHOR:    Carsten Dominik
#+EMAIL:     carsten at orgmode dot org
#+LANGUAGE:  en
#+STARTUP:   hidestars
#+LINK:      git http://orgmode.org/w/?p=org-mode.git;a=commit;h=%s
#+LINK:      doc http://orgmode.org/worg/doc.html#%s
#+OPTIONS:   H:3 num:nil toc:t \n:nil @:t ::t |:t ^:t *:t TeX:t author:nil <:t LaTeX:t
#+KEYWORDS:  Org Org-mode Emacs outline planning note authoring project plain-text LaTeX HTML
#+DESCRIPTION: Org Org-mode Emacs Changes ChangeLog release notes
#+HTML_HEAD:     <link rel="stylesheet" href="org-changes.css" type="text/css" />

#+BEGIN_HTML
<div id="top"><p><em>Org mode is for keeping notes, maintaining TODO lists, planning
projects, and authoring documents with a fast and effective plain-text system.</em></p></div>
#+END_HTML

* Version 8.2

** Incompatible changes

*** =xdg-open= has been removed again from =org-file-apps-defaults-gnu=

    This did not work properly in some environments as xdg-open is
    desktop specific.

** Important bug fixes

*** Match string for sparse trees can now contain a slash in a property value

    You can now have searches like SOMEPROP="aaa/bbb".  Until now,
    this would break because the slash would be interpreted as the
    separator starting a TOTO match string.

** New features

*** Changes in the default packages loaded for LaTeX

    - =rotating= is now a default package, to support sideways tables.
    - =amsmath= is a default package
    - =eucal= package removed, no longer needed since amsmath is
      present

    Furthermore, the manual now specifically notes if an additional
    package is needed for one of the documented attributes.

*** Microsoft Outlook support has been added to /org-mac-link.el/

    Thanks to Marc McLean for this patch.

*** Lazy autoloading of /org-id.el/ to follow links

    When following a link that has an =id:= prefix, /org-id.el/ will
    now automatically be loaded.

    Thanks to Oleh for this patch

*** New functions for paragraph motion
    
    The commands =C-down= and =C-up= now invoke special commands
    that use knowledge from the org-elements parser to move the cursor
    in a paragraph-like way.

    Thanks to Nicolas Goaziou for the implementation.

*** New agenda fortnight view

    The agenda has now, in addition to day, week, month, and year
    views, also a fortnight view covering 14 days.

    Thanks to Michael Gauland for the implementation.

** New options

*** New option: [[doc:org-special-ctrl-o][org-special-ctrl-o]]

    This variable can be used to turn off the special behavior of
    =C-o= in tables.
    

* Version 8.1

** Incompatible changes

*** Combine org-mac-message.el and org-mac-link-grabber into org-mac-link.el

Please remove calls to =(require 'org-mac-message)= and =(require
'org-mac-link-grabber)= in your =.emacs= initialization file.  All you
need now is =(require 'org-mac-link)=.

Additionally, replace any calls to =ogml-grab-link= to
=org-mac-grab-link=.  For example, replace this line:

: (define-key org-mode-map (kbd "C-c g") 'omgl-grab-link)

with this:

: (define-key org-mode-map (kbd "C-c g") 'org-mac-grab-link)

*** HTML export: Replace =HTML_HTML5_FANCY= by =:html-html5-fancy= (...)

Some of the HTML specific export options in Org <8.1 are either nil or
t, like =#+HTML_INCLUDE_STYLE=.  We replaced these binary options with
option keywords like :html-include-style.

So you need to replace

: #+HTML_INCLUDE_STYLE: t

by 

: #+OPTIONS: :html-include-style t

Options affected by this change: =HTML5_FANCY=, =HTML_INCLUDE_SCRIPTS=
and =HTML_INCLUDE_STYLE=.

** Important bugfixes

*** [[doc:org-insert-heading][org-insert-heading]] has been rewritten and bugs are now fixed
*** The replacement of disputed keys is now turned of when reading a date

** New features

*** You can now use =xdg-open= to control how to open files
*** =C-c ^ x= will now sort checklist items by their checked status

See [[doc:org-sort-list][org-sort-list]]: hitting =C-c ^ x= will put checked items at the end
of the list.
*** Various LaTeX export enhancements

- Support SVG images
- Support for .pgf files
- LaTeX Babel blocks can now be exported as =.tikz= files
- Allow =latexmk= as an option for [[doc:org-latex-pdf-process][org-latex-pdf-process]]
- When using =\usepackage[AUTO]{inputenc}=, AUTO will automatically be
  replaced with a coding system derived from =buffer-file-coding-system=.
- The dependency on the =latexsym= LaTeX package has been removed, we
  now use =amssymb= symbols by default instead.

*** Remapping =forward-paragraph= and =backward-paragraph=

=forward-paragraph= and =backward-paragraph= are now remapped to
[[doc:org-forward-element][org-forward-element]] and [[doc:org-backward-element][org-backward-element]] respectively.
E.g. hitting =C-<down>= on a headline will move to the next headline.

*** New entities in =org-entities.el=
    
Add support for ell, imath, jmath, varphi, varpi, aleph, gimel, beth,
dalet, cdots, S (ยง), dag, ddag, colon, therefore, because, triangleq,
leq, geq, lessgtr, lesseqgtr, ll, lll, gg, ggg, prec, preceq,
preccurleyeq, succ, succeq, succurleyeq, setminus, nexist(s), mho,
check, frown, diamond.  Changes loz, vert, checkmark, smile and tilde.

** New options

*** New option [[doc:org-bookmark-names-plist][org-bookmark-names-plist]]

This allows to specify the names of automatic bookmarks.
*** New option [[doc:org-agenda-ignore-drawer-properties][org-agenda-ignore-drawer-properties]]

This allows more flexibility when optimizing the agenda generation.
See http://orgmode.org/worg/agenda-optimization.html for details.
*** New option: [[doc:org-html-link-use-abs-url][org-html-link-use-abs-url]] to force using absolute URLs

This is an export/publishing option, and should be used either within
the =#+OPTIONS= line(s) or within a [[doc:org-publish-project-alist][org-publish-project-alist]].

Setting this option to =t= is needed when the HTML output does not
allow relative URLs.  For example, the =contrib/lisp/ox-rss.el=
library produces a RSS feed, and RSS feeds need to use absolute URLs,
so a combination of =:html-link-home "..." and :html-link-use-abs-url
t= is required---see the configuration example in the comment section
of =ox-rss.el=.

*** New option [[doc:org-babel-ditaa-java-cmd][org-babel-ditaa-java-cmd]]

This makes java executable configurable for ditaa blocks.

*** New options [[doc:org-babel-latex-htlatex][org-babel-latex-htlatex]] and [[doc:org-babel-latex-htlatex-packages][org-babel-latex-htlatex-packages]]

This enables SVG generation from latex code blocks.

*** New option: [[doc:org-habit-show-done-alwyays-green][org-habit-show-done-alwyays-green]]

See [[http://lists.gnu.org/archive/html/emacs-orgmode/2013-05/msg00214.html][this message]] from Max Mikhanosha.

*** New option: [[doc:org-babel-inline-result-wrap][org-babel-inline-result-wrap]]

If you set this to the following

: (setq org-babel-inline-result-wrap "$%s$")

then inline code snippets will be wrapped into the formatting string.

** New contributed packages

- =ox-bibtex.el= by Nicolas Goaziou :: an utility to handle BibTeX
     export to both LaTeX and HTML exports.  It uses the [[http://www.lri.fr/~filliatr/bibtex2html/][bibtex2html]]
     software.

- =org-screenshot.el= by Max Mikhanosha :: an utility to handle
     screenshots easily from Org, using the external tool [[http://freecode.com/projects/scrot][scrot]].

* Older changes

For older Changes, see [[file:Changes_old.org][old changes]].
