#+title: Org Emacs lisp Package Archive
#+setupfile: setup.org
#+description: Org: an Emacs Mode for Notes, Planning and Authoring
#+include: "./resources/preamble.html" export html

* Org Emacs lisp Package Archive (deprecated)
  :PROPERTIES:
  :CUSTOM_ID: introduction
  :END:

For versions <= 9.5, [[https://orgmode.org][orgmode.org]] hosts Org ELPA archives.

*Beware that no new Org versions will be released on Org ELPA after
9.5.*

Add this to your Emacs init file to be able to list the Org mode
archives:

#+BEGIN_SRC emacs-lisp
(require 'package)
(add-to-list 'package-archives '("org" . "https://orgmode.org/elpa/") t)
#+END_SRC

Then =M-x list-packages RET= will list both the latest =org= and
=org-plus-contrib= packages.

- =org= :: Contains the same set of files that are included in GNU
  Emacs.

- =org-plus-contrib= :: Contains these files plus all contribs files,
  the ones you used to find in =contrib/= from the [[https://git.sr.ht/~bzg/org-contrib][git repo]].

* Installation
  :PROPERTIES:
  :CUSTOM_ID: installation
  :END:

By default, Emacs loads packages *after* it loads your Emacs init file.

We recommend intializing packages as /early/ as possible in your Emacs
init file so that your Org configuration will be correctly handled:

#+BEGIN_SRC emacs-lisp :exports code
;; -*- emacs-lisp -*-
(package-initialize)                ;; Initialize & Install Package
;; (setq org-...)                   ;; Your custom settings
#+END_SRC

The package initialization should happen *before* you require Org and
set any Org options.

Also, you may want to set up Package correctly before initializing it:

#+BEGIN_SRC emacs-lisp :exports code
  ;; -*- emacs-lisp -*-
  (unless package-archive-contents    ;; Refresh the packages descriptions
    (package-refresh-contents))
  (setq package-load-list '(all))     ;; List of packages to load
  (unless (package-installed-p 'org)  ;; Make sure the Org package is
    (package-install 'org))           ;; installed, install it if not
  (package-initialize)                ;; Initialize & Install Package
  ;; (setq org-...)                   ;; Your custom settings
#+END_SRC

See the [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Packages.html][GNU Emacs Package manual]] for details.

* Questions?
  :PROPERTIES:
  :CUSTOM_ID: questions
  :END:

Report any problem and ask any question on the Org mode [[https://orgmode.org/worg/org-mailing-list.html][mailing list]].
