#+title: Org Emacs lisp Package Archive
#+author: Bastien Guerry
#+date: 2012-09-26
#+language:  en
#+startup:   hidestars
#+options:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t author:nil <:t LaTeX:t
#+keywords:  Org Emacs outline planning note authoring project plain-text LaTeX HTML
#+description: Org: an Emacs Mode for Notes, Planning, and Authoring
#+macro: updown #+HTML: <div class="move"><a onclick="goToByScroll('$1');return false;" href="#">< $1</a> · <a onclick="goToByScroll('$2');return false;" href="#">$2 ></a></div>
#+html_head:     <link rel="stylesheet" href="org.css" type="text/css" />

#+begin_export html
<div id="top"><p><em>Org mode is for keeping notes, maintaining TODO lists, planning
projects, and authoring documents with a fast and effective plain-text system.<br />

<span id="top2">It was created by <a href="https://staff.science.uva.nl/~dominik/">Carsten Dominik</a> in 2003, who still maintains it with the help from <a href="https://orgmode.org/org.html#History-and-Acknowledgments">thousands</a> of users.</span></em></p></div>
#+end_export

* Org Emacs lisp Package Archive
  :PROPERTIES:
  :CUSTOM_ID: introduction
  :END:

[[https://orgmode.org][orgmode.org]] hosts Org ELPA archives.

Add this to your Emacs init file to be able to list the Org mode archives:

#+BEGIN_SRC emacs-lisp
(require 'package)
(add-to-list 'package-archives '("org" . "https://orgmode.org/elpa/") t)
#+END_SRC

Then =M-x list-packages RET= will list both the latest =org= and
=org-plus-contrib= packages.

- =org= :: contains the same set of files that are included in GNU Emacs.

- =org-plus-contrib= :: contains these files plus all contribs files, the
     ones you find in =contrib/= from the [[https://orgmode.org/cgit.cgi/org-mode.git/log/][git repo]].

** Move
   :PROPERTIES:
   :ID:       move
   :HTML_CONTAINER_CLASS: move
   :END:

{{{updown(introduction,installation)}}}

* Installation
  :PROPERTIES:
  :CUSTOM_ID: installation
  :END:

By default, Emacs loads packages *after* it loads your Emacs init file.

We recommend intializing packages as /early/ as possible in your Emacs init
file so that your Org configuration will be correctly handled:

#+BEGIN_SRC emacs-lisp :exports code
  ;; -*- emacs-lisp -*-
  (package-initialize)                ;; Initialize & Install Package
  ;; (setq org-...)                   ;; Your custom settings
#+END_SRC

The package initialization should happen *before* you require Org and set
any Org options.

Also, you may want to set up Package correctly before initializing it:

#+BEGIN_SRC emacs-lisp :exports code
  ;; -*- emacs-lisp -*-
  (unless package-archive-contents    ;; Refresh the packages descriptions
    (package-refresh-contents))
  (setq package-load-list '(all))     ;; List of packages to load
  (unless (package-installed-p 'org)  ;; Make sure the Org package is
    (package-install 'org))           ;; installed, install it if not
  (package-initialize)                ;; Initialize & Install Package
  ;; (setq org-...)                   ;; Your custom settings
#+END_SRC

See the [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Packages.html][GNU Emacs Package manual]] for details.

** Move
   :PROPERTIES:
   :ID:       move
   :HTML_CONTAINER_CLASS: move
   :END:

{{{updown(introduction,questions)}}}

* Questions?
  :PROPERTIES:
  :CUSTOM_ID: questions
  :END:

If you think the package are not updated, please check [[https://orgmode.org/elpa/build-org-pkg.txt][this file]].

Report any problem and ask any question on the Org mode [[https://orgmode.org/community.html][mailing list]].


** Move
   :PROPERTIES:
   :ID:       move
   :HTML_CONTAINER_CLASS: move
   :END:

{{{updown(installation,questions)}}}
