#+title:       Org mode for Emacs
#+author:    Carsten Dominik
#+email:     carsten at orgmode dot org
#+setupfile: setup.org
#+description: Org: an Emacs Mode for Notes, Planning, and Authoring
#+include: "./resources/preamble.html" export html

#+include: "./resources/normal-outline-3.html" export html

#+begin_export html
<style>
  .columns .outline-3 {
    width: 15rem;
  }
</style>
#+end_export

#+begin_export html
<div class="banner large" itemscope itemtype="http://schema.org/SoftwareApplication">
  <div class="title">
    <img src="/resources/img/org-mode-unicorn.svg"
         alt="Org unicorn logo" itemprop="image"/>
    <h2>
      <span itemprop="name">Org Mode</span>
      <p class="subtitle">Convenient <span itemprop="applicationCategory">plain text markup</span> and more</p>
    </h2>
  </div>
  <div class="comment" style="align-self: flex-end">
    <p style="font-style: italic">
      An extensible major mode for
      <a href="https://www.gnu.org/software/emacs/" style="color: #333; font-weight: bold">Emacs</a>.</p>
    <br/>
    <p>Org mode is for keeping notes, maintaining to-do lists, planning
      projects, authoring documents, computational notebooks, literate
      programming, and more &mdash; in a fast and effective plain text
      system.</p>
    <p class="bubble">
      Support via&ensp;
      <a href="https://liberapay.com/bzg" title="Donations always help"
         style="font-weight: bold; color: #7d6f37">
        <img class="inline" src="/resources/img/external/librepay.svg" alt="LibrePay logo"/>
        LibrePay</a>&ensp;
      <a href="https://github.com/sponsors/bzg" title="Donations always help"
         style="font-weight: bold; color: #222">
        <img class="inline" src="/resources/img/external/github.svg" alt="GitHub logo"/>
        GitHub</a>&emsp14;
      or&emsp14;
      <a href="https://www.paypal.com/paypalme/bzg/10" title="Donations always help"
         style="font-weight: bold; color: #253b80">
        <img class="inline" src="/resources/img/external/paypal.svg" alt="Paypal logo"/>
        PayPal</a></p>
  </div>
  <meta itemprop="operatingSystem" content="Linux, MacOS, Windows">
  <meta itemprop="softwareVersion" content="9.3.8">
  <meta itemprop="datePublished" content="2020-08-07">
  <meta itemprop="url" content="https://orgmode.org">
  <meta itemprop="screenshot" content="https://orgmode.org/resources/img/main.svg">
</div>
<div class="banner slim green inline">
  <p style="width: 90vw">
    Created by
    <a target="new" href="https://staff.science.uva.nl/~dominik/">Carsten Dominik</a>
    in <a target="new" href="/manual/History-and-Acknowledgments.html">2003</a>,
    maintained by <a target="new" href="http://bzg.fr">Bastien Guerry</a>
    and developed by
    <a href="https://orgmode.org/org.html#History-and-Acknowledgments">many others</a>.</p>
</div>
#+end_export

* Highlights
:PROPERTIES:
:HTML_CONTAINER_CLASS: columns no-heading
:END:
** Features
@@html:<a href="features.html">@@
[[file:resources/img/stars.svg]]

There are /dozens/ of them.
@@html:</a>@@
** Install
@@html:<a href="install.html">@@
[[file:resources/img/install.svg]]

What are you waiting for?
@@html:</a>@@
** Quickstart
@@html:<a href="quickstart.html">@@
[[file:resources/img/quickstart.svg]]

Start using Org. You'll never stop.
@@html:</a>@@
** Contribute
@@html:<a href="contribute.html">@@
[[file:resources/img/contribute.svg]]

Yes. Do this.
@@html:</a>@@

* Elaboration + demo image :ignore:
Org is a highly flexible structured plain text file format, composed of a few
simple, yet versatile, structures --- constructed to be both [[https://karl-voit.at/2017/09/23/orgmode-as-markup-only/][simple enough for the
novice]] and [[http://howardism.org/Technical/Emacs/literate-devops.html][powerful enough for the expert]].

#+attr_html: :style max-width:min(45rem, 80vw)
[[file:resources/img/main.svg]]

* Further reading

As well at the [[file:quickstart.org][quickstart]] and [[file:manual/index.html][manual]], there's also
a [[file:guide/index.html][guide]], and a wealth of community-written docs on [[https://orgmode.org/worg/][Worg]] .

Once you've used Org for a bit, you'll know it's great --- it's actually
so great that there have been [[https://orgmode.org/worg/org-papers.html][(scientific) papers]] written about the value of Org
for [[https://en.wikipedia.org/wiki/Reproducibility#Reproducible_research][reproducible research]].

* More Org

Org's /de facto/ mimetype is =text/org=. Most systems don't recognise ~.org~ by
default, but they usually can be made to without too much effort.

While much of Org's features are self-contained, there are a number of [[file:tools.org][tools]]
which work with Org.
#+begin_center
#+attr_html: :class btn
[[file:tools.org][Tools which work with Org]]
#+end_center

* [[https://orgmode.org/worg/][Worg]], a /World/ of Org
There's so much one may want to say about Org-mode, that it's impossible to
cleanly keep track of it here. That's why [[https://orgmode.org/worg/][Worg]] was created.

It's a Git repository of =.org= pages published as an HTML website. Think of it as
a wiki. New contributors are welcome, just create a user on [[https://code.orgmode.org][code.orgmode.org]] and
ask to be added as a collaborator.

#+BEGIN_SRC shell
~$ git clone https://code.orgmode.org/bzg/worg.git
#+END_SRC

This is a community effort to provide useful information pertaining to Org-mode.
You'll find it linked to in quite a few places. For instance, it contains:
+ [[https://orgmode.org/worg/org-faq.html][The FAQ]]
+ [[https://orgmode.org/worg/org-hacks.html][Org hacks]]
+ [[https://orgmode.org/worg/org-tutorials/index.html][A list of tutorials]]
+ [[https://orgmode.org/worg/doc.html][Documentation on all hooks, commands, and options]]
+ ...and much more

* Org in the wild
** Chatting about Org
You can connect with other org-thusiasts via IRC at ~#orgmode~ on [[https://freenode.net/][freenode]].

There's also a mailing list which you can [[https://lists.gnu.org/mailman/listinfo/emacs-orgmode][subscribe]] to, and browse the [[https://orgmode.org/list][archives]]
([[https://lists.gnu.org/archive/html/emacs-orgmode/][alternative]]) of.
** Writing about Org
+ [[https://www.viktorbengtsson.com/blog/org-mode-for-writers/][Org-mode for writers]]
+ [[https://blog.jethro.dev/posts/how_to_take_smart_notes_org/][How To Take Smart Notes With Org-mode · Jethro Kuan]]
+ [[https://opensource.com/article/20/4/emacs-org-mode][Use Emacs Org mode to easily create LaTeX documents | Opensource.com]]
+ [[http://www.howardism.org/Technical/Emacs/orgmode-wordprocessor.html][Org as a Word Processor]]
+ [[http://www.howardism.org/Technical/Emacs/literate-devops.html][Literate DevOps]]
** Talking about Org
+ [[https://www.youtube.com/watch?v=oJTwQvgfgMM][Google Tech Talk]] (2008) :: Delivered by Carsten Dominick.
+ Max Planck Institute for Neurological Research (2010) :: Recording lost to the
  sands of time.
+ [[http://twit.tv/show/floss-weekly/136][FLOSS Weekly]] (2010) :: Interview of Carsten Dominic.
+ [[https://orgmode.org/worg/org-tutorials/org-screencasts/ghm2011-demo.html][GHM Paris]] (2011) :: Org Demo by Bastien Guerry.
+ [[https://www.youtube.com/watch?v=wiMSzI6VHhM][GPN12]] (2012) :: Florain Adamsky's in-depth presentation ([[http://florian.adamsky.it/research/talks/gpn12/GPN12-Emacs-Org-mode.pdf][slides]]).
+ [[https://www.youtube.com/watch?v=SzA2YODtgK4][Thoughtbot]] (2016) :: Getting started with Org Mode by Harry Schwartz.
+ [[https://www.youtube.com/watch?v=0g9BcZvQbXU][YouTube]] (2019) :: Consistent Technical Documents Using Emacs and Org Mode, by Mike Hamrick.
