#+title: Org mode for Emacs
#+setupfile: setup.org
#+description: Org: an Emacs Mode for Notes, Planning and Authoring
#+html_head: <link rel="stylesheet" href="/resources/style/index.min.css" type="text/css" />
#+html_head: <link rel="preload" href="/resources/img/org-mode-unicorn.svg" as="image" type="image/svg+xml">
#+include: "./resources/preamble.html" export html

#+html_head: <link rel="stylesheet" href="/resources/style/org-demo.min.css" type="text/css" />
#+include: "./resources/normal-outline-3.html" export html

#+begin_export html
<div class="banner hero" itemscope itemtype="https://schema.org/SoftwareApplication">
  <img src="/resources/img/org-mode-unicorn.svg"
       alt="Org unicorn logo" itemprop="image"/>
  <div>
    <h2>
      <span itemprop="name">Org Mode</span>
      <p class="subtitle">Your life in plain text</p>
    </h2>
    <p>
      A <a href="https://www.gnu.org/software/emacs/" style="color: inherit; font-weight: bold; font-style: italic;"
           title="An extensible, customizable, free/libre text editor">GNU Emacs</a>
      major mode for <span itemprop="applicationCategory"> keeping notes, authoring documents,
      computational notebooks, literate programming, maintaining to-do lists, planning
      projects, and more &mdash; in a fast and effective plain text
      system.</p>
      <p><a title="Install from GNU ELPA" href="https://elpa.gnu.org/packages/org.html"><img src="https://elpa.gnu.org/packages/org.svg" alt="Install from GNU ELPA" /></a>
	<a title="How to report a bug" href="https://orgmode.org/manual/Feedback.html"><img src="/resources/img/badge-report-bug.svg" alt="How to report a bug" /></a>
	<a title="Email the Org-mode mailing list" href="mailto:emacs-orgmode@gnu.org"><img src="/resources/img/badge-feedback.svg" alt="Email the Org-mode mailing list" /></a>
	<a title="sr.ht project page" href="https://sr.ht/~bzg/org"><img src="/resources/img/badge-srht-project.svg" alt="sr.ht project page"/></a></p>
    <p><span style="color: #567b70;font-family: var(--sans);font-size: 0.9em;">Repository</span>
      <code>git clone git://git.sv.gnu.org/emacs/org-mode.git</code></p>
    <p><span style="color: #567b70;font-family: var(--sans);font-size: 0.9em;">Report bug</span>
      <code>M-x org-submit-bug-report RET</code></p>
    <p class="bubble">
      Support via&ensp;
      <a href="https://liberapay.com/org-mode" title="Donations always help"
         style="font-weight: bold; display: inline-block">
        <img class="inline" src="/resources/img/external/librepay.svg" alt="Liberapay logo"/>
        Liberapay</a></p>
    <meta itemprop="operatingSystem" content="Linux, MacOS, Windows">
    <meta itemprop="softwareVersion" content="9.3.8">
    <meta itemprop="datePublished" content="2020-08-07">
    <meta itemprop="url" content="https://orgmode.org">
  </div>
</div>
<div class="banner slim grey faded inline">
  <p style="width:90vw; color:#515151">
    Created by
    <a target="new" href="https://staff.science.uva.nl/~dominik/"
       style="font-weight:500; color:inherit">Carsten Dominik</a>
    in <a target="new" href="/manual/History-and-Acknowledgments.html" style="color:#6e6e6e">2003</a>,
    maintained by <a target="new" href="https://bzg.fr/en/" style="font-weight:500; color:inherit">Bastien Guerry</a>
    and developed by
    <a href="https://orgmode.org/org.html#History-and-Acknowledgments" style="color:#6e6e6e">many others</a>.</p>
</div>
#+end_export

* Highlights
  :PROPERTIES:
  :HTML_CONTAINER_CLASS: columns no-heading
  :END:

** Features
   @@html:<a href="features.html">@@
   #+attr_html: :alt Three stars :title Delve into the possibilities
   [[file:resources/img/stars.svg]]

   @@html:</a>@@

** Install
   @@html:<a href="https://orgmode.org/org.html#Installation">@@
   #+attr_html: :alt Downwards facing arrow :title What are you waiting for?
   [[file:resources/img/install.svg]]

   @@html:</a>@@

** Quickstart
   @@html:<a href="quickstart.html">@@
   #+attr_html: :alt Running stickfigure :title Start using Org. You'll never stop.
   [[file:resources/img/quickstart.svg]]

   @@html:</a>@@

** Contribute
   @@html:<a href="worg/org-contribute.html">@@
   #+attr_html: :alt Git branch symbol :title Yes. Do this.
   [[file:resources/img/contribute.svg]]

   @@html:</a>@@

* Elaboration + demo image                                        :ignore:

  #+attr_html: :style margin-top:2rem;
  Org is a highly flexible structured plain text file format, composed
  of a few simple, yet versatile, structures --- constructed to be both
  [[https://karl-voit.at/2017/09/23/orgmode-as-markup-only/][simple enough for the novice]] and [[http://howardism.org/Technical/Emacs/literate-devops.html][powerful enough for the expert]].

  Get a glimpse of the expressive power Org offers in the example below.
  Click the headings and links to discover how Org intelligently folds structural content.

  #+include: org-demo.html export html

* Further reading
  :PROPERTIES:
  :CUSTOM_ID: reading
  :END:

Beyond the [[file:quickstart.org][quickstart]] and the [[file:manual/index.html][manual]], Org has a [[file:guide/index.html][guide]] and a wealth of
community-written documentation on [[https://orgmode.org/worg/][Worg]] .

Nearly every Org user has a story to tell about how Org enables and
empowers them --- some have found it so useful that they have written
[[https://orgmode.org/worg/org-papers.html][(scientific) papers]] about the value of Org for conducting [[https://en.wikipedia.org/wiki/Reproducibility#Reproducible_research][reproducible
research]]. Some have produced third party tools to enjoy Org outside of
Emacs, such as mobile applications.

* More Org
  :PROPERTIES:
  :CUSTOM_ID: more
  :END:

The /de facto/ mimetype for Org files is =text/org=. Org files use the
~.org~ extension. Most operating systems don't know to open ~.org~ files
in Emacs, but they can be configured to do so without much effort.

While the reference implementation of Org in Emacs lisp is by far the
most featureful, there are many additional [[file:tools.org][tools]] that work with Org.

#+begin_center
#+attr_html: :class btn
[[file:tools.org][Tools that work with Org]]
#+end_center

* [[https://orgmode.org/worg/][Worg]], a /World/ of Org
  :PROPERTIES:
  :CUSTOM_ID: worg
  :END:

Org and Org-mode have so many use cases that it is simply not possible
to easily document them, let alone show them all off on a single page.
As a result, [[https://orgmode.org/worg/][Worg]] serves as a community wiki and provides a place to
document and share information about all aspects of using and working
with Org.

For example, Worg contains:

- [[https://orgmode.org/worg/org-faq.html][The FAQ]]
- [[https://orgmode.org/worg/org-hacks.html][Org hacks]]
- [[https://orgmode.org/worg/org-tutorials/index.html][A list of tutorials]]
- [[https://orgmode.org/worg/doc.html][Documentation on all hooks, commands and options]]
- [[https://orgmode.org/worg/org-in-the-wild.html][Org in the wild]]
- /...and much more/

Worg is maintained as a Git repository of Org files that are published
as an HTML website.  New [[https://orgmode.org/worg/worg-git.html#contribute-to-worg][contributors are welcome]].

#+BEGIN_SRC shell
~$ git clone https://git.sr.ht/~bzg/worg
#+END_SRC

* Joining the mailing list
  :PROPERTIES:
  :CUSTOM_ID: mailing-list
  :END:

Org mailing list is the central place where to connect with Org
community.  You can [[https://lists.gnu.org/mailman/listinfo/emacs-orgmode][subscribe to the list]] and browse the list archive 
on [[https://list.orgmode.org][list.orgmode.org]] or on [[https://lists.gnu.org/archive/html/emacs-orgmode/][this mailman page]].

If you are not a subscriber to the list, you can still send an email
to [[mailto:emacs-orgmode@gnu.org][emacs-orgmode@gnu.org]], we will add you to the whitelist of people
who can reach the list.

You can [[https://orgmode.org/worg/org-mailing-list.html][read more on the mailing list]] and more information on [[https://orgmode.org/worg/org-web-social.html][Org news
on the social web]].

You can also connect with other org-thusiasts via IRC at ~#org-mode~ on
[[https://libera.chat/][Libera.Chat]].

The full [[https://orgmode.org/worg/contributors.html][list of contributors]] to Org mode is maintained in /Worg/ and
you can also check the manual's [[https://orgmode.org/org.html#History-and-Acknowledgments][acknowledgments]].

* Doom, Spacemacs, Scimax and popular configs
  :PROPERTIES:
  :CUSTOM_ID: configs
  :END:

The Emacs starter kits [[https://github.com/hlissner/doom-emacs][Doom]], [[https://www.spacemacs.org/][Spacemacs]] and [[https://github.com/jkitchin/scimax][Scimax]] come with a curated
set of packages and configurations that aim to enhance Org mode (and
Emacs more generally) for particular use cases.  They include Org
along with integrations between =org-mode= and other modes (such as
=evil-mode=).  Here are links to the current packages included with
[[https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/packages.el][Doom]], and [[https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bemacs/org/packages.el][Spacemacs]].  /Scimax/ is deeply integrated with Org so a good
place to start is the [[https://github.com/jkitchin/scimax/blob/master/scimax.org#org-mode][manual]].  /Doom/ installs a version of Org that is
close to the development ~HEAD~, while /Spacemacs/ and /Scimax/ track org
elpa.

Starter kits often make significant changes to the default user
experience for Emacs.  If you are looking for something closer to
vanilla Emacs there are popular configs such as [[https://github.com/purcell/emacs.d/blob/master/lisp/init-org.el][Purcell's emacs.d]] that
include org-mode customization and Org-related packages.

* In Other Editors
  :PROPERTIES:
  :CUSTOM_ID: editors
  :END:

While the full set of Org [[file:features.html][features]] is currently exclusive to Emacs,
basic functionality for Org files has been implemented for a variety
of editors.  Here are some extensions for other editors that enable
support for Org files.

- *Vim* : [[https://github.com/kristijanhusak/orgmode.nvim][orgmode.nvim]], [[https://github.com/jceb/vim-orgmode][vim-orgmode]], and [[https://github.com/axvr/org.vim][org.vim]]
- *Atom* : [[https://atom.io/packages/org-mode][org-mode]]
- *VS Codium* : [[https://github.com/vscode-org-mode/vscode-org-mode][vscode-org-mode]]
