#+TITLE: Install | Org Mode
#+setupfile: setup.org
#+description: Get started with Org: an Emacs Mode for Notes, Planning, and Authoring
#+include: "./resources/preamble.html" export html

* Installation
The reference implementation of Org is part of [[https://www.gnu.org/software/emacs/][Emacs]].
If you already have Emacs installed, you can start using =org-mode= right away!

#+begin_center
#+attr_html: :class btn
[[https://www.gnu.org/software/emacs/][Get Emacs]]
#+end_center

You can install the latest version of Org as a package by invoking
~M-x package-install RET org RET~ once you have configured Emacs
to include [[file:elpa.html][Org ELPA]] as a package repository.

Alternatively you can download the package as a [[https://orgmode.org/org-9.4.tar.gz][tar.gz]] or [[https://orgmode.org/org-9.4.zip][zip]] archive.

The bleeding-edge development version or Org is available at [[https://code.orgmode.org/bzg/org-mode][code.orgmode.org]].
You can clone the repo via:
#+BEGIN_SRC shell
~$ git clone https://code.orgmode.org/bzg/org-mode.git
#+END_SRC

Daily snapshots of the development version are released as [[https://orgmode.org/org-latest.tar.gz][tar.gz]] or [[https://orgmode.org/org-latest.zip][zip]] files.

Worg has documentation about [[https://orgmode.org/worg/dev/org-build-system.html][build options]] and about how to [[https://orgmode.org/worg/org-faq.html#keeping-current-with-Org-mode-development][stay on the bleeding edge]].

There are also many packages that augment Org available on [[https://melpa.org/#/?q=org-mode&sort=downloads&asc=false][MELPA]].

** Get started

Once you're ready to Org, check out the [[file:quickstart.org][Quickstart]]
page for an overview of the syntax.

* Doom, Spacemacs, and popular configs
The Emacs starter kits /Doom/ and /Spacemacs/ come with a curated set of packages and configurations that may be
more familiar to users coming from other editors (e.g. Vim). They include Org along with integrations between
=org-mode= and other modes (such as =evil-mode=). Here are links to the current packages included with
[[https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/packages.el][Doom]], and
[[https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bemacs/org/packages.el][Spacemacs]].
/Doom/ installs a version of Org that is close to the development ~HEAD~.

Popular configs like [[https://github.com/purcell/emacs.d/blob/master/lisp/init-org.el][Purcell's emacs.d]]
often include org-mode customization, and Org-related packages.

* In Other Editors
While the full set of Org [[file:features.html][features]] is
currently exclusive to Emacs, basic functionality for Org files has
been implemented for a variety of editors.  Here are extensions for
other editors that enable support for Org files.
+ [[https://github.com/jceb/vim-orgmode][Vim]]
+ [[https://atom.io/packages/org-mode][Atom]]
+ [[https://github.com/vscode-org-mode/vscode-org-mode][VSCode]]
+ [[https://packagecontrol.io/packages/orgmode][Sublime]]
