#+TITLE: Install | Org Mode
#+setupfile: setup.org
#+description: Get started with Org: an Emacs Mode for Notes, Planning, and Authoring
#+include: "./resources/preamble.html" export html

* Installation
Org's core is part of [[https://www.gnu.org/software/emacs/][Emacs]], if you have Emacs, you have =org-mode= available to use.

#+begin_center
#+attr_html: :class btn
[[https://www.gnu.org/software/emacs/][Get Emacs]]
#+end_center

You can also add org as a package, in order to run the latest version, using
~M-x package-install RET org RET~ (see [[file:elpa.html][Org ELPA]]).
Alternatively you can download the package as a [[https://orgmode.org/org-9.3.7.tar.gz][tar.gz]] or [[https://orgmode.org/org-9.3.7.zip][zip]] archive.

The bleeding-edge development version can be viewed at [[https://code.orgmode.org/bzg/org-mode][code.orgmode.org]] or by
cloning the repo:
#+BEGIN_SRC shell
~$ git clone https://code.orgmode.org/bzg/org-mode.git
#+END_SRC
Daily snapshots of the development version: [[https://orgmode.org/org-latest.tar.gz][tar.gz]] or [[https://orgmode.org/org-latest.zip][zip]].

Worg will tell you more on the [[https://orgmode.org/worg/dev/org-build-system.html][build options]] and on how to [[https://orgmode.org/worg/org-faq.html#keeping-current-with-Org-mode-development][stay on the bleeding edge]].

One will also find a large number of packages to augment Org on [[https://melpa.org/#/?q=org-mode&sort=downloads&asc=false][MELPA]].

** Get started

When you're ready to start trying out Org, take a look at the [[http://orgmode.tecosaur.com/quickstart.html][Quickstart]] page
for an overview of the syntax.

* Doom, Spacemacs, and popular configs
The Emacs kits /Doom/ and /Spacemacs/ both come with default setups for Org --- i.e.
Org and a selection of packages. Here's what you get with [[https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/packages.el][Doom]], and likewise
[[https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bemacs/org/packages.el][Spacemacs]]. It's worth noting that /Doom/ installs a version of Org close to the
development ~HEAD~.

Popular configs like [[https://github.com/purcell/emacs.d/blob/master/lisp/init-org.el][Purcell's emacs.d]] will also often include org-mode
customisations, and Org-related packages.

* In Other Editors
While the full set of Org [[file:features.html][features]] is currently exclusive to Emacs, a
number of extensions exist for other editors which provide basic functionality.
Here are some extensions available for:
+ [[https://github.com/jceb/vim-orgmode][Vim]]
+ [[https://atom.io/packages/org-mode][Atom]]
+ [[https://github.com/vscode-org-mode/vscode-org-mode][VSCode]]
+ [[https://packagecontrol.io/packages/orgmode][Sublime]]
