#+title:     Org mode for Emacs -- Talks and presentations
#+author:    Bastien
#+email:     bzg at gnu dot org
#+startup:   hidestars
#+language:  en
#+options:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t author:nil <:t LaTeX:t
#+keywords:  Org Org-mode Emacs outline planning note authoring project plain-text LaTeX HTML
#+description: Org Org-mode Emacs Talks about Org-mode
#+macro: updown #+HTML: <div class="move"><< <a onclick="goToByScroll('$1');return false;" href="#">$1</a><br /><br />>> <a onclick="goToByScroll('$2');return false;" href="#">$2</a></div>
#+html_head:     <link rel="stylesheet" href="org.css" type="text/css" />

#+begin_export html
<div id="top"><p><em>Org mode is for keeping notes, maintaining TODO lists, planning
projects, and authoring documents with a fast and effective plain-text system.</em></p></div>
#+end_export

* GoogleTech Talk by Carsten Dominik (2008)
  :PROPERTIES:
  :CUSTOM_ID:       google-tech-talk
  :END:

Here is the video of the [[http://www.youtube.com/user/GoogleTechTalks][Google Tech Talk]] about Org mode that I gave on
July 15th, 2008 on the Google campus in Mountain View, California.

#+begin_export html
<iframe width="560" height="315" src="https://www.youtube.com/embed/oJTwQvgfgMM?rel=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
#+end_export

Thanks to [[http://emacspeak.sourceforge.net/raman/][T.V. Raman]] and [[http://technical-dresese.blogspot.com/][Andrew Hyatt]] for being my hosts during my stay.

You can check [[https://orgmode.org/worg/org-tutorials/org-screencasts/org-mode-google-tech-talk.html#sec-2][the timeline of the topics covered]] by this talk.

** Move
   :PROPERTIES:
   :CUSTOM_ID:       move
   :HTML_CONTAINER_CLASS: move
   :END:

{{{updown(google-tech-talk,org-for-scientists)}}}


* At the Max Planck Institute for Neurological Research (2010)
  :PROPERTIES:
  :CUSTOM_ID:       org-for-scientists
  :END:

#+begin_export html
<iframe class="iframe" src="http://player.vimeo.com/video/33725204?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=0" width="402" height="302" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
#+end_export

This is a talk presented on February 8th 2010 at the Max Planck Institute
for Neurological Research in Cologne, Germany (http://nf.mpg.de).  Check
[[http://www.nf.mpg.de/orgmode/guest-talk-dominik.html][this page]] for details.

** Move
   :PROPERTIES:
   :CUSTOM_ID:       move
   :HTML_CONTAINER_CLASS: move
   :END:

{{{updown(google-tech-talk,floss-weekly)}}}


* Interview of Carsten Dominik at [[http://twit.tv/show/floss-weekly/136][FLOSS Weekly]] (2010)
  :PROPERTIES:
  :CUSTOM_ID:       floss-weekly
  :END:

#+begin_export html
<iframe class="iframe" src="http://twit.tv/embed/8239" width="480" height="320" scrolling="no" marginwidth="0" marginheight="0" hspace="0" align="middle" frameborder="0"></iframe>
#+end_export



** Move
   :PROPERTIES:
   :CUSTOM_ID:       move
   :HTML_CONTAINER_CLASS: move
   :END:

{{{updown(org-for-scientists,ghm2011)}}}


* Bastien's presentation at GHM Paris (2011)
  :PROPERTIES:
  :CUSTOM_ID:       ghm2011
  :END:

#+begin_export html
<iframe class="iframe" src="http://player.vimeo.com/video/30721952?title=0&amp;byline=0&amp;portrait=0" width="480" height="354" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
#+end_export

This presentation was given during the GNU Hackers Meeting in Paris, 2011.

Thanks to Ludovic Courtès who invited me and all the GNU people who made
this event possible.

You can check [[https://orgmode.org/worg/org-tutorials/org-screencasts/ghm2011-demo.html#sec-2][the timeline of the topics covered]] by this talk.

** Move
   :PROPERTIES:
   :CUSTOM_ID:       move
   :HTML_CONTAINER_CLASS: move
   :END:

{{{updown(floss-weekly,gpn12)}}}


* Florian Adamsky's in-depth presentation at [[https://entropia.de/GPN12][GPN12]] (2012)
  :PROPERTIES:
  :CUSTOM_ID:       gpn12
  :END:

#+begin_export html
<iframe width="420" height="315" src="https://www.youtube.com/watch?v=wiMSzI6VHhM" frameborder="0" allowfullscreen></iframe>
#+end_export

The slides are available [[http://florian.adamsky.it/research/talks/gpn12/GPN12-Emacs-Org-mode.pdf][as PDF here]].

** Move
   :PROPERTIES:
   :CUSTOM_ID:       move
   :HTML_CONTAINER_CLASS: move
   :END:

{{{updown(ghm2011,gpn12)}}}



