#+TITLE: Org mode: Enlaces
#+AUTHOR: Bastien
#+LANGUAGE:  es
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t author:nil <:t LaTeX:t
#+KEYWORDS:  Org Emacs outline planificación nota autoría proyecto texto-plano LaTeX HTML
#+DESCRIPTION: Org: un Modo Emacs para Notas, Planificación y Autoría
#+STYLE:     <base href="http://orgmode.org/es/" />
#+STYLE:     <link rel="icon" type="image/png" href="org-mode-unicorn.png" />
#+STYLE:     <link rel="stylesheet" href="http://orgmode.org/org.css" type="text/css" />
#+STYLE:     <link rel="publisher" href="https://plus.google.com/102778904320752967064" />

* Charlas acerca de Org mode

  Carsten Dominik dió una charla en GoogleTech acerca de Org mode y
  otra en el [[http://www.nf.mpg.de/orgmode/guest-talk-dominik.html][Max Planck Institute for Neurological Research]]. En FLOSS
  Weekly [[tp://twit.tv/floss136][number 136]] Randal Schwartz entrevista a Carsten acerca de Org
  mode.

  Bastien presentó Org en el [[http://fosdem.org/2011/][FOSDEM 2011]], con la ayuda de Stefan
  Vollmar (presentando un caso de uso desde su laboratorio) y
  Sébastien Vauban (presentando Org Babel). Se puede encontrar el PDF
  de las presentaciones [[http://lumiere.ens.fr/~guerry/u/org-fosdem-presentation-beamer.pdf][aquí]].  En Agosto de 2011, Bastien también dió
  una presentación similar (pero actualizada) presentación en el GNU
  Hackers Meeting en París.

  Visite todas las charlas en la [[file:talks.org][página dedicada a "charlas"]].

* Org desde el móvil

  [[http://mobileorg.ncogni.to/][MobileOrg]] es una excelente aplicación libre para leer y modificar
  ficheros Org desde la calle, usando un iPhone, y sincronizar los
  cambios con su ordenador. Visite la [[http://mobileorg.ncogni.to/][página de Richard]].

  Matt Jones está desarrollando una aplicación compatible para Android,
  y dicho proyecto [[http://wiki.github.com/matburt/mobileorg-android/][alojado aquí]].
