#+TITLE: Org mode: Download and Install
#+AUTHOR: Bastien
#+LANGUAGE:  es
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t author:nil <:t LaTeX:t
#+KEYWORDS:  Org Emacs outline planificación nota autoría proyecto texto-plano LaTeX HTML
#+DESCRIPTION: Org: un Modo Emacs para Notas, Planificación y Autoría
#+STYLE:     <base href="http://orgmode.org/es/" />
#+STYLE:     <link rel="icon" type="image/png" href="org-mode-unicorn.png" />
#+STYLE:     <link rel="stylesheet" href="http://orgmode.org/org.css" type="text/css" />
#+STYLE:     <link rel="publisher" href="https://plus.google.com/102778904320752967064" />

* Actual Versión: Org 7.8.11

La actual versión es la 7.8.11. Para ver qué ha cambiado en recientes
entregas, visite esta detallada lista de [[file:Changes.html][cambios (inglés)]].

Este paquete funciona en GNU Emacs 24, 23 y 22, y (con restricciones
menores) en XEmacs 21. Emacs 22.2 funciona con la versión de Org mode
4.67d, Emacs 23.1 con 6.21b. La última versión del desarrollo de Emacs
normalmente contiene una versión reciente, pero puede haber algo de
retraso con respecto a la entrega que hay en el sitio web.

* Descargas

** La distribución estándar

Descarga un [[file:org-7.8.11.zip][fichero zip]] o un [[file:org-7.8.11.tar.gz][archivo tar comprimido con gz]]. Estos
archivos contienen los ficheros Lisp =org*.el= y la documentación en
formatos PDF y (TeX)Info. Sigue las instrucciones para su [[http://orgmode.org/manual/Installation.html#Installation][Instalación]] y
[[http://orgmode.org/manual/Activation.html#Activation][Activación]].

** La versión en desarrollo

Se puede chequear la última versión del desarrollo de Org (junto con
todas las entregas que se han hecho) usando git. El repositorio git es [[http://orgmode.org/w/org-mode.git][navegable
online]]. En cualquier momento se puede obtener una [[http://orgmode.org/w/org-mode.git/snapshot][fotografía]] de los
ficheros que hay en él. Para obtener un clon local del repositorio,
escribe esto (desde la línea de comandos):

: git clone git://orgmode.org/org-mode.git

Algo más de información puede encontrarse en la [[http://orgmode.org/worg/org-faq.php][FAQ]], bajo la pregunta [[http://orgmode.org/worg/org-faq.php#keeping-current-with-Org mode-development]["How do I
keep current with Org mode development?"]] (inglés). Para personas que
no pueden usar git, se proporciona una entrega de ficheros
actualizados cada día y correspondientes a la última versión del git
en formato [[file:org-latest.zip][zip]] o [[file:org-latest.tar.gz][tar.gz]]. De manera alternativa, también se puede
descargar un [[http://orgmode.org/w/org-mode.git/snapshot][snapshot en tar.gz]] desde el servidor orgmode.org

** Distribuciones Alternativas

Hay varias distribuciones alternativas de Org. Algunas de estas están
más actualizadas que otras, así comprueba si el siguiente paquete
realmente tiene una versión reciente.

   - El [[http://packages.debian.org/sid/main/org-mode][paquete Debian]] mantenido por Sebastien Delafond.
   - Hay también un paquete en [[http://aur.archlinux.org/packages.php?do_Details&ID=18206][Archlinux]], por Jiyunatori.
   - La versión en desarrollo de [[https://savannah.gnu.org/projects/emacs/][Emacs]] contiene una versión más o
     menos reciente.
   - El [[http://pdb.finkproject.org/pdb/package.php/org-mode][paquete Fink]] para Mac OS X por Jesse Alama.
   - El [[https://launchpad.net/~hexmode/+archive][paquete Ubuntu]] por Mark A. Hershberger.
