#+title:     Org mode for Emacs -- Votre vie en texte brut
#+setupfile: ../setup.org
#+language:  fr
#+description: Org: an Emacs Mode for Notes, Planning, and Authoring
#+html_head: <link rel="stylesheet" href="/resources/style/index.css" type="text/css" />
#+html_head: <link rel="preload" href="/resources/img/org-mode-unicorn.svg" as="image" type="image/svg+xml">
#+include: "../resources/preamble.html" export html

#+include: "../resources/normal-outline-3.html" export html

#+begin_export html
<style>
  .columns .outline-3 {
    width: 15rem;
  }
</style>
#+end_export

#+begin_export html
<div class="banner hero" itemscope itemtype="http://schema.org/SoftwareApplication">
  <img src="/resources/img/org-mode-unicorn.svg"
       alt="Org unicorn logo" itemprop="image"/>
  <div>
    <h2>
      <span itemprop="name">Org Mode</span>
      <p class="subtitle">Langage de balisage <span itemprop="applicationCategory">léger et pratique</span></p>
    </h2>
    <p>
      Un mode principal, extensible, et open-source pour
      <a href="https://www.gnu.org/software/emacs/" style="color: inherit; font-weight: bold; font-style: italic;">Emacs</a>.</p>
    <p>Org mode sert à prendre des notes, gérer des to-do lists, planifier
      des projets, rédiger des documents, des calepins de calculs, faire
      de la programmation littéraire, … le tout dans un système rapide et efficace,
      en texte simple.</p>
    <p class="bubble">
      Nous soutenir via&ensp;
      <a href="https://liberapay.com/bzg" title="Les dons sont toujours utiles"
         style="font-weight: bold;">
        <img class="inline" src="/resources/img/external/librepay.svg" alt="logo de Liberapay"/>
        Liberapay</a>&ensp;
      <a href="https://github.com/sponsors/bzg" title="Les dons sont toujours utiles"
         style="font-weight: bold;">
        <img class="inline" src="/resources/img/external/github.svg" alt="logo de GitHub"/>
        GitHub</a>&emsp14;
      ou&emsp14;
      <a href="https://www.paypal.com/paypalme/bzg/10" title="Les dons sont toujours utiles"
         style="font-weight: bold;">
        <img class="inline" src="/resources/img/external/paypal.svg" alt="Logo de Paypal"/>
        PayPal</a></p>
    <meta itemprop="operatingSystem" content="Linux, MacOS, Windows">
    <meta itemprop="softwareVersion" content="9.3.8">
    <meta itemprop="datePublished" content="2020-08-07">
    <meta itemprop="url" content="https://orgmode.org">
    <meta itemprop="screenshot" content="https://orgmode.org/resources/img/main.svg">
  </div>
  </div>
  <div class="banner slim green inline">
    <p style="width: 90vw">
      Crée par
      <a target="new" href="https://staff.science.uva.nl/~dominik/">Carsten Dominik</a>
      en <a target="new" href="/manual/History-and-Acknowledgments.html">2003</a>,
      maintenu par <a target="new" href="http://bzg.fr">Bastien Guerry</a>
      et développé par
      <a href="https://orgmode.org/org.html#History-and-Acknowledgments">beaucoup d'autres</a>.</p>
  </div>
#+end_export

* Points forts
:PROPERTIES:
:HTML_CONTAINER_CLASS: columns no-heading
:END:
** Fonctionalités
@@html:<a href="features.html">@@
[[file:../resources/img/stars.svg]]

Explorez les possibilités.
@@html:</a>@@
** Installation
@@html:<a href="install.html">@@
[[file:../resources/img/install.svg]]

Qu'est-ce que vous attendez ?
@@html:</a>@@
** Démarrage rapide
@@html:<a href="quickstart.html">@@
[[file:../resources/img/quickstart.svg]]

Commencez à utiliser Org. Vous ne pourrez plus vous arrêter.
@@html:</a>@@
** Contribuer
@@html:<a href="contribute.html">@@
[[file:../resources/img/contribute.svg]]

Oui oui, faites le.
@@html:</a>@@

* Elaboration + demo image :ignore:

Org utilise du texte brut structuré et flexible, composé de quelques
structures simples mais polyvalentes : simples pour le débutant,
puissantes pour l'expoert.

#+attr_html: :style max-width:min(45rem, 80vw) :alt An example org file, showing a few basic elements
[[file:../resources/img/main.svg]]

* En savoir plus

À part le [[file:../quickstart.org][quickstart]] et le [[https://orgmode.org/manual/][manuel]], il existe un [[https://orgmode.org/guide/][guide]], et pléthore de
documentations rédigées par la communauté sur [[https://orgmode.org/worg/][Worg]].

Presque tous les utilisateurs d'Org ont une histoire, montrant à quel point Org les a aidé.
À tel point que certains ont rédigé des [[https://orgmode.org/worg/org-papers.html][papiers (de recherche)]] à propos de l'utilisation d'Org
dans le cadre de [[https://en.wikipedia.org/wiki/Reproducibility#Reproducible_research][recherche reproductible]]. Certains ont même produit des outils
externes pour profiter d'Org en dehors d'Emacs, dont des applications mobiles.

* Plus d'Org

Le type mime /par défaut/ d'Org est =text/org=, et les fichiers Org
utilisent l'extension ~.org~. Bien que la pluspart des systèmes ne
reconnaissent pas les fichiers ~.org~ par défaut, ils peuvent souvent
être configurés pour les ouvrir dans emacssans difficultés.

Bien que l'implémentation de référence d'Org, en Lisp Emacs, est de
loin celle qui a le plus de fonctionalités, il existe quelques
[[file:../tools.org][outils]] tiers.

#+begin_center
#+attr_html: :class btn
[[file:../tools.org][Outils fonctionnant avec Org]]
#+end_center

* [[https://orgmode.org/worg/][Worg]], l'écosystème Org

[[https://orgmode.org/worg/][Worg]] (pour /World/ of Org) est la plateforme d'expression
communautaire d'Org.

Org et Org-mode sont utilisables dans beaucoup de contextes, pour
beaucoup de choses, il est impossible de tout documenter ici, ou en
une page. On a donc crée [[https://orgmode.org/worg/][Worg]], un wiki communautaire permettant de
partager les différents moyens d'utiliser Org.

Worg contient entre autre:
+ [[https://orgmode.org/worg/org-faq.html][La FAQ]]
+ [[https://orgmode.org/worg/org-hacks.html][Org hacks]]
+ [[https://orgmode.org/worg/org-tutorials/index.html][Une liste de tutoriels]]
+ [[https://orgmode.org/worg/doc.html][La documentations de tous les hooks, commandes, et options]]
+ [[https://orgmode.org/worg/org-in-the-wild.html][Org en action]]
+ ...et bien plus

C'est un dépôt Git, de fichiers Org publiés en HTML sur un site
web. Les nouvelles contributions sont bienvenues, pour celà créez-vous
un compte sur [[https://code.orgmode.org][code.orgmode.org]] et demandez à être ajouté comme
collaborateur.

#+BEGIN_SRC shell
~$ git clone https://code.orgmode.org/bzg/worg.git
#+END_SRC

* Discutter d'Org
Vous pouvez vous connecter à d'autres org-tousiastes via IRC sur les
salons ~#org-mode~ et ~#org-mode-fr~ on [[https://freenode.net/][freenode]].

Il existe aussi une mailing list à laquelle vous pouvez vous [[https://lists.gnu.org/mailman/listinfo/emacs-orgmode][abonner]],
ou visiter ses [[https://orgmode.org/list][archives]] ici sur =orgmode.org= ou via les
[[https://lists.gnu.org/archive/html/emacs-orgmode/][archives GNU listserv]].
