#+TITLE:     Org: Votre Vie en Texte Brut
#+EMAIL:     carsten at orgmode dot org
#+LANGUAGE:  fr
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t author:nil <:t LaTeX:t
#+KEYWORDS:  Org Emacs outline planneur note publication projet text brut LaTeX HTML
#+DESCRIPTION: Org: un mode Emacs pour la prise de notes, la planification et la publication
#+STYLE:     <base href="http://orgmode.org/fr/" />
#+STYLE:     <link rel="stylesheet" href="http://orgmode.org/org.css" type="text/css" />

* Org: un mode d'Emacs pour les notes, la gestion de tâches et la publication

# See http://jonraasch.com/blog/a-simple-jquery-slideshow for a slideshow
#+begin_html
<script language="Javascript">
function banner() { } ; b = new banner() ; n = 0
b[n++]= "<a href='http://orgmode.org/img/screenshots/org-plot1.jpg' alt='' rel='lightbox'></a>"
b[n++]= "<a href='http://orgmode.org/img/screenshots/org-R3.jpg' alt='' rel='lightbox'></a>"
b[n++]= "<a href='http://orgmode.org/img/screenshots/org-spreadsheet-system.jpg' alt='' rel='lightbox' class='active'/>"
b[n++]= "<a href='http://orgmode.org/worg/images/screenshots/org-mode-publishing.jpg' alt='' rel='lightbox'></a>"
b[n++]= "<a href='http://orgmode.org/worg/images/screenshots/davison-minimal-research.png' alt='' rel='lightbox'></a>"
b[n++]= "<a href='http://orgmode.org/img/screenshots/big-table.jpg' alt='' rel='lightbox'></a>"
b[n++]= "<a href='http://orgmode.org/img/screenshots/column-view-big-project.jpg' alt='' rel='lightbox'></a>"
b[n++]= "<a href='http://orgmode.org/img/screenshots/org-plot-page-in-worg.jpg' alt='' rel='lightbox'></a>"
b[n++]= "<a href='http://orgmode.org/img/screenshots/bernt3.jpg' alt='' rel='lightbox'></a>"
b[n++]= "<a href='http://orgmode.org/img/screenshots/column-view.jpg' alt='' rel='lightbox'></a>"
b[n++]= "<a href='http://orgmode.org/img/screenshots/customize.jpg' alt='' rel='lightbox'></a>"
b[n++]= "<a href='http://orgmode.org/img/screenshots/using-date-time-charles-cave.jpg' alt='' rel='lightbox'></a>"
b[n++]= "<a href='http://orgmode.org/img/screenshots/vmap-org-export-to-pdf2.jpg' alt='' rel='lightbox'></a>"
b[n++]= "<a href='http://orgmode.org/img/screenshots/vmap-org-sources-iimage-mode2.jpg' alt='' rel='lightbox'></a>"
b[n++]= "<a href='http://orgmode.org/img/screenshots/grades.jpg' alt='' rel='lightbox'></a>"
b[n++]= "<a href='http://orgmode.org/img/screenshots/org_andreas.jpg' alt='' rel='lightbox'></a>"
b[n++]= "<a href='http://orgmode.org/img/screenshots/web_site_org_code.jpg' alt='' rel='lightbox'></a>"
b[n++]= "<a href='http://orgmode.org/img/screenshots/org-mode-zenburn.jpg' alt='' rel='lightbox'></a>"
b[n++]= "<a href='http://orgmode.org/img/screenshots/weekly-agenda-view-zenburn.jpg' alt='' rel='lightbox'></a>"
b[n++]= "<a href='http://orgmode.org/img/screenshots/david_o_toole.jpg' alt='' rel='lightbox'></a>"
b[n++]= "<a href='http://orgmode.org/img/screenshots/orgmode-inlinetasks.jpg' alt='' rel='lightbox' class='active'/>"
b[n++]= "<a href='http://orgmode.org/img/screenshots/clocking-and-overlays.jpg' alt='' rel='lightbox'></a>"
i=Math.floor(Math.random() * n) ; 
document.write( b[i] )
</script>
#+end_html

Org-mode est une outil pour prendre des notes, maintenir des TODO listes,
faire de la gestion de projet, de la planification et de la publication
avec un système en text brut, simple et effectif.

* Rester simple... et faire encore plus

- Simplicité :: Fondamentalement, Org-mode est un simple outliner pour la
                prise de notes et la gestion de listes.  Vous pouvez
                apprendre les bases pour l'utiliser en [[http://orgmode.org/worg/org-tutorials/orgtutorial_dto-fr.html][cinq minutes]].  C'est
                peut-être tout ce dont vous avez besoin, et Org-mode ne
                vous imposera pas de fonctions plus complexes.

- Portabilité :: Les fichiers Org sont en [[http://fr.wikipedia.org/wiki/Fichier_texte][texte brut]].  Vous pouvez les voir
                 et les lire avec n'importe quel éditeur, ou ajouter et
                 extraire des données supplémentaires avec des scripts
                 faits main.  Vos données ne seront jamais captives d'un
                 obscur format propriétaire.  Org-mode tourne sous [[http://www.gnu.org/software/emacs/][Emacs]],
                 qui est disponible pour presque toutes les plates-formes.

- Profondeur :: Org-mode ne vous laissera pas tomber quand vous aurez
                besoin de plus qu'un outliner.  L'ensemble complet des
                fonctionnalités est à la fois large et profond, facile à
                atteindre, et non intrusif.  La [[http://orgmode.org/worg/org-faq.php][réponse typique]] à la
                question «/Puis-je faire X ?/» est "/Oui !/".

- Flexibilité :: Org-mode est comme un couteau Suisse. Les gens l'utilisent
                 pour la méthodologie [[http://members.optusnet.com.au/~charles57/GTD/orgmode.html][Getting Things Done (GTD)]], comme un
                 [[http://newartisans.com/2007/08/using-org-mode-as-a-day-planner/][agenda]], comme un [[http://sachachua.com/wp/2008/01/18/outlining-your-notes-with-org/][carnet de notes]], pour la publication Web
                 et PDF, et bien plus.

- Support :: Org-mode est [[http://orgmode.org/manual/index.html][largement documenté]] et de nombreux [[http://orgmode.org/worg/org-tutorials/index.php][tutoriels]]
             portent un éclairage sur des fonctionnalités
             particulières.  Org-mode est soutenu par une [[id:0B280B26-A3AB-4E5C-B4EE-B7FFC52C4D26][liste de
             discussion active]] où les questions reçoivent des réponses
             rapides et efficaces.

- C'est libre ! :: Org est un [[http://fr.wikipedia.org/wiki/Logiciel_libre][logiciel libre]], publié sous la licence [[http://www.gnu.org/licenses/licenses.html#GPL][GNU
                   GPL version 3]], comme [[http://www.gnu.org/software/emacs/][GNU Emacs]].

Si vous voulez savoir ce que les utilisateurs ont dit d'org-mode, faites un
tour sur [[http://orgmode.org/worg/org-quotes.php][la page des citations]].
