#+TITLE:     Org mode for Emacs -- Présentations et vidéos
#+AUTHOR:    Bastien
#+EMAIL:     bzg at gnu dot org
#+STARTUP:   hidestars
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t author:nil <:t LaTeX:t
#+KEYWORDS:  Org Org-mode Emacs outline planning note authoring project plain-text LaTeX HTML
#+DESCRIPTION: Org Org-mode Emacs Talks about Org-mode
#+MACRO: updown #+HTML: <div class="move"><< <a onclick="goToByScroll('$1');return false;" href="#">$1</a><br /><br />>> <a onclick="goToByScroll('$2');return false;" href="#">$2</a></div>
#+HTML_HEAD:     <link rel="stylesheet" href="http://orgmode.org/org.css" type="text/css" />

#+BEGIN_EXPORT HTML
<div id="top"><p><em>Org mode permet de prendre des notes, de maintenir des listes TODO, de
planifier des projets et de publier des documents, le tout en texte brut.</em></p></div>
#+END_EXPORT

* GoogleTech Talk par Carsten Dominik (2008)
  :PROPERTIES:
  :ID:       google-tech-talk
  :END:

#+begin_export html
<iframe class="iframe" width="420" height="315" src="http://www.youtube.com/embed/oJTwQvgfgMM" frameborder="0" allowfullscreen></iframe>
#+end_export

Voici la vidéo du [[http://www.youtube.com/user/GoogleTechTalks][Google Tech Talk]] que j'ai donné le 15 juillet 2008 sur le
campus de Google à Mountain View, California.

Merci à [[http://emacspeak.sourceforge.net/raman/][T.V. Raman]] et [[http://technical-dresese.blogspot.com/][Andrew Hyatt]] de m'avoir hébergé pendant mon séjour.

Vous pouvez lire la [[http://orgmode.org/worg/org-tutorials/org-screencasts/org-mode-google-tech-talk.html#sec-2][frise chronologique des sujets abordés]] pendant cette
présentation.

** Move
   :PROPERTIES:
   :ID:       move
   :HTML_CONTAINER_CLASS: move
   :END:

{{{updown(google-tech-talk,org-pour-scientifiques)}}}

* Au Max Planck Institute pour la Recherche Neurologique (2010)
  :PROPERTIES:
  :ID:       org-pour-scientifiques
  :END:

#+begin_export html
<iframe class="iframe" src="http://player.vimeo.com/video/33725204?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=0" width="402" height="302" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
#+end_export

Cette présentation a eu lieu le 8 février 2010 au Max Planck Institute pour
la Recherche Neurologique à Cologne, en Allemagne (http://nf.mpg.de).  Voir
[[http://www.nf.mpg.de/orgmode/guest-talk-dominik.html][cette page]] pour les détails.

** Move
   :PROPERTIES:
   :ID:       move
   :HTML_CONTAINER_CLASS: move
   :END:

{{{updown(google-tech-talk,floss-weekly)}}}

* Interview de Carsten Dominik par [[http://twit.tv/show/floss-weekly/136][FLOSS Weekly]] (2010)
  :PROPERTIES:
  :ID:       floss-weekly
  :END:

#+begin_export html
<iframe class="iframe" src="http://twit.tv/embed/8239" width="480" height="320" scrolling="no" marginwidth="0" marginheight="0" hspace="0" align="middle" frameborder="0"></iframe>
#+end_export

** Move
   :PROPERTIES:
   :ID:       move
   :HTML_CONTAINER_CLASS: move
   :END:

{{{updown(org-pour-scientifiques,ghm2011)}}}

* Présentation de Bastien au GHM Paris (2011)
  :PROPERTIES:
  :ID:       ghm2011
  :END:

#+begin_export html
<iframe class="iframe" src="http://player.vimeo.com/video/30721952?title=0&amp;byline=0&amp;portrait=0" width="480" height="354" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
#+end_export

Cette présentation fut donnée pendant le GNU Hackers Meeting de Paris
en 2011.

Merci à Ludovic Courtès de m'avoir invité et à tous les contributeurs du
projet GNU qui ont permis que cet événements ait lieu.

Vous pouvez lire la [[http://orgmode.org/worg/org-tutorials/org-screencasts/ghm2011-demo.html#sec-2][frise chronologique des sujets abordés]] pendant cette
présentation.

** Move
   :PROPERTIES:
   :ID:       move
   :HTML_CONTAINER_CLASS: move
   :END:

{{{updown(floss-weekly,gpn12)}}}
* Présentation de Florian Adamsky's au [[https://entropia.de/GPN12][GPN12]] (2012)
  :PROPERTIES:
  :ID:       gpn12
  :END:

#+begin_export html
<iframe width="420" height="315" src="http://www.youtube.com/embed/mUSoo4UaKBo" frameborder="0" allowfullscreen></iframe>
#+end_export

Le diapomara est téléchargeable [[http://florian.adamsky.it/research/talks/gpn12/GPN12-Emacs-Org-mode.pdf][en PDF ici]].

** Move
   :PROPERTIES:
   :ID:       move
   :HTML_CONTAINER_CLASS: move
   :END:

{{{updown(ghm2011,gpn12)}}}



