#+TITLE:     Org mode for Emacs -- Talks and presentations
#+AUTHOR:    Bastien
#+EMAIL:     bzg at gnu dot org
#+STARTUP:   hidestars
#+LANGUAGE:  ja
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t author:nil <:t LaTeX:t
#+KEYWORDS:  Org Org-mode Emacs outline planning note authoring project plain-text LaTeX HTML
#+DESCRIPTION: Org Org-mode Emacs Talks about Org-mode
#+MACRO: updown #+HTML: <div class="move"><< <a onclick="goToByScroll('$1');return false;" href="#">$1</a><br /><br />>> <a onclick="goToByScroll('$2');return false;" href="#">$2</a></div>
#+HTML_HEAD:     <link rel="stylesheet" href="../org.css" type="text/css" />

#+BEGIN_EXPORT
<div id="top"><p><em>Org-mode は、ノートの保存、TODOリストの管理、プロジェクト計画のためのモードです。高速で効率的なプレーンテキストのシステムを使ってファイルを編集します。</em></p></div>
#+END_EXPORT

* Carsten Dominik 氏による GoogleTech Talk の講演 (2008)
  :PROPERTIES:
  :ID:       google-tech-talk
  :END:

#+begin_export
<iframe class="iframe" width="420" height="315" src="http://www.youtube.com/embed/oJTwQvgfgMM" frameborder="0" allowfullscreen></iframe>
#+end_export

[[http://research.google.com/video.html][Google Tech Talk]] で Carsten Dominik 氏が、org-mode について講演したときの映像です。2008年7月15日に、カリフォルニア州マウンテンビューにあるグーグルキャンパスで行われました。

Carsten Dominik 氏は、[[http://emacspeak.sourceforge.net/raman/][T.V. Raman]] 氏と [[http://technical-dresese.blogspot.com/][Andrew Hyatt]] 氏へ「滞在中にお世話になりました。ありがとう。」と感謝のメッセージを送りました。

講演の[[http://orgmode.org/worg/org-tutorials/org-screencasts/org-mode-google-tech-talk.html#sec-2][進行表]]を、対応する動画とともに確認できます。

** Move
   :PROPERTIES:
   :ID:       move
   :HTML_CONTAINER_CLASS: move
   :END:

{{{updown(google-tech-talk,org-for-scientists)}}}


* * Carsten 氏による the Max Planck Institute for Neurological Research での講演(2010)
  :PROPERTIES:
  :ID:       org-for-scientists
  :END:

#+begin_export
<iframe class="iframe" src="http://player.vimeo.com/video/33725204?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=0" width="402" height="302" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
#+end_export

この講演は、2010年2月8日に the Max Planck Institute for Neurological Research in Cologne, Germany (http://nf.mpg.de) で行われました。詳細は[[http://www.nf.mpg.de/orgmode/guest-talk-dominik.html][こちら]]のページをチェックしてください。

** Move
   :PROPERTIES:
   :ID:       move
   :HTML_CONTAINER_CLASS: move
   :END:

{{{updown(google-tech-talk,floss-weekly)}}}


* [[http://twit.tv/show/floss-weekly/136][FLOSSウィークリィ]] の Carsten Dominik 氏へのインタビュー (2010)
  :PROPERTIES:
  :ID:       floss-weekly
  :END:

#+begin_export
<iframe class="iframe" src="http://twit.tv/embed/8239" width="480" height="320" scrolling="no" marginwidth="0" marginheight="0" hspace="0" align="middle" frameborder="0"></iframe>
#+end_export



** Move
   :PROPERTIES:
   :ID:       move
   :HTML_CONTAINER_CLASS: move
   :END:

{{{updown(org-for-scientists,ghm2011)}}}


* Bastien氏による org-mode のプレゼンテーション (2011)
  :PROPERTIES:
  :ID:       ghm2011
  :END:

#+begin_export
<iframe class="iframe" src="http://player.vimeo.com/video/30721952?title=0&amp;byline=0&amp;portrait=0" width="480" height="354" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
#+end_export

このプレゼンテーションは、2012年にパリで開催されたGNUハッカーズミーティングで行われました。

Bastien氏をこのミーティングに招待したLudovic Courtès氏と、ミーティングを支えたすべてのGNUな人々に感謝します。

講演の[[http://orgmode.org/worg/org-tutorials/org-screencasts/ghm2011-demo.html#sec-2][進行表]]を、対応する動画とともに確認できます。

** Move
   :PROPERTIES:
   :ID:       move
   :HTML_CONTAINER_CLASS: move
   :END:

{{{updown(floss-weekly,gpn12)}}}

* Florian Adamsky's in-depth presentation at [[https://entropia.de/GPN12][GPN12]] (2012)
  :PROPERTIES:
  :ID:       gpn12
  :END:

#+begin_export
<iframe width="420" height="315" src="http://www.youtube.com/embed/mUSoo4UaKBo" frameborder="0" allowfullscreen></iframe>
#+end_export

The slides are available [[http://florian.adamsky.it/research/talks/gpn12/GPN12-Emacs-Org-mode.pdf][as PDF here]].

** Move
   :PROPERTIES:
   :ID:       move
   :HTML_CONTAINER_CLASS: move
   :END:

{{{updown(ghm2011,gpn12)}}}



